// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hosts} from '../models';

export function ApplyHosts(arg1:hosts.HostWorkspace):Promise<void>;

export function CanWriteHosts():Promise<boolean>;

export function EnsureWriteAccess():Promise<void>;

export function GetHosts():Promise<hosts.HostWorkspace>;

export function SaveHosts(arg1:hosts.HostWorkspace):Promise<void>;
