// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hosts} from '../models';
import {update} from '../models';

export function ApplyHosts(arg1:hosts.HostWorkspace):Promise<void>;

export function CanWriteHosts():Promise<boolean>;

export function CheckForUpdate():Promise<update.Info>;

export function DownloadUpdate(arg1:update.Info):Promise<string>;

export function EnsureWriteAccess():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetHosts():Promise<hosts.HostWorkspace>;

export function GetUpdateSettings():Promise<update.Settings>;

export function InstallUpdate(arg1:string):Promise<void>;

export function SaveHosts(arg1:hosts.HostWorkspace):Promise<void>;

export function SaveUpdateSettings(arg1:update.Settings):Promise<void>;
