// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyHosts(arg1) {
  return window['go']['main']['App']['ApplyHosts'](arg1);
}

export function CanWriteHosts() {
  return window['go']['main']['App']['CanWriteHosts']();
}

export function EnsureWriteAccess() {
  return window['go']['main']['App']['EnsureWriteAccess']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function SaveHosts(arg1) {
  return window['go']['main']['App']['SaveHosts'](arg1);
}
